import os
CURRENT_DIRECTORY_PATH = os.path.dirname(__file__)
COMPLEXITY_LEXICON_PATH = CURRENT_DIRECTORY_PATH + "/lexicon.tsv"
TRAINING_FILES = [CURRENT_DIRECTORY_PATH+"/BenchLS.txt", CURRENT_DIRECTORY_PATH+"/BenchPS.txt"]
